import NavBar from "@/components/NavBar";
import "./globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <div className="body-wrapper">
          <div className="body-nav-wrapper">
            <NavBar />
          </div>
          <div className="body-main-wrapper">{children}</div>
        </div>
      </body>
    </html>
  );
}
